services:
  - type: web
    name: tts-api
    env: python
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --workers 2 --threads 4 --timeout 300 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
